apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
    spec:
      containers:
      - name: app
        image: rsayre14/csc468:MySQLServer
        resources:
          requests:
            cpu: 10m
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: my_root_password
        ports:
        - containerPort: 3306
